### ISSUE TITLE
temp

### ISSUE THREAD

**Issue by dghu123** [dghu123/stat-comp#1]

**Comment by karamar000** [comment]
Hey David :)

**Comment by dghu123** [comment]
this is pretty fast actually

**Comment by dghu123** [comment]
hallo

**Comment by karamar000** [comment]
Yo

**Comment by karamar000** [comment]
<3

**Comment by dghu123** [comment]
<3 <3

**Comment by dghu123** [comment]
how's life on the other side of the world

**Comment by karamar000** [comment]
I'm temporarily enjoying the life of a bum: listening to podcasts, shopping at thrift stores, cooking, reading, and watching movies. I worked out with my mom a few times...so sore! Also been thinking about you a lot. How's life on the other side of the world? I'm sure you have more exciting adventures to talk about!

**Comment by karamar000** [comment]
<3

**Comment by dghu123** [comment]
today we went to a really old part of suzhou - so basically the government rebuilt the whole city but kept like two streets for historic/tourist purposes

it's a really pretty street that follows a canal right next to it and lots of bridges; very crowded though

then we went to a garden - "the humble administrators garden" which was also really pretty - it was like a big lake with a lot of small footpaths and tall rocks and classic chinese architecture

thought about you a lot, really wishing you were here with me

<3 find anything good at the thrift store? ;)

**Comment by karamar000** [comment]
Happy New Year from Michigan ~smooch~ 
<3

**Comment by karamar000** [comment]
Happy New Year from Michigan 
--smooch--   <3

**Comment by karamar000** [comment]
I ended up ordering a copy of Carcassonne. Can't wait to play it with you! I also bought some tights that you might think are nice ;)

I looked up the places that you went to. They look so beautiful! I can just imagine you enjoying the landscape like a handsome wanderer above the sea of fog, looking pensively over the water. I love hearing about your adventures from the other side of the world. What else have you been up to?

I hope you had a wonderful New Year! Did you do anything for New Years Eve? Or is this another holiday that you don't really celebrate haha. I drank wine and ate cheese with my mom, but I couldn't help thinking of you. I'm so thankful for the wonderful moments we shared together this year. You are the ultimate highlight to my 2017.   <3

**Comment by dghu123** [comment]
board games and tights - how did I get so lucky? :3

I actually forgot about new year's until I was in bed '\_(: \ )_/' we didn't do anything for new year's eve. I thought about kissing you though. Yeah, that was a great night :)

today we went to a country club / farm type thing? there was a restaurant and a tea house but also cows and horses and a gun range and farmland. Shot some guns. America! but in china. The food was also really good - probably sourced from the surrounding farms. We had lunch with fresh milk and hot pot and other chinese food; then we said hello to the cows who made the milk.

Happy New Year Kara. I treasure every minute I've spent together with you. Here's to another year of love and cuddling <3

**Comment by karamar000** [comment]
Thinking about you a lot <3 
It's good to hear about all of your adventures. Sounds like you're having a great time! What was the adventure for today?

It's SO COLD here. I'm literally wearing two pairs of pants and two pairs of socks, while under 3 blankets...not all of the layers are necessary tbh, but I'll leave you wondering about where that line of necessity lies. I could really use a cuddle buddy right about now :)

**Comment by dghu123** [comment]
thinking about snuggling you and keeping you warm and toasty :)

yesterday we went to shanghai and saw the part of shanghai that was ceded to the europeans after the opium wars - "the bund".  it was kinda funny because all the european constructed buildings looked very historically european but had all these chinese flags all over it just so you knew it was chinese now.

today we're flying to beijing. it won't be very interesting :/ beijing is going to be really cold. wish you were here to cuddle :3

**Comment by karamar000** [comment]
Looks like we’re both flying home today. Beijing is still more interesting than me going home. I’m flying into “winter storm Grayson” though :| so it’s going to be an adventure. If only we could cuddle under one of those airplane blankets :)

Thinking of you and hoping that you’re staying warm :3

**Comment by karamar000** [comment]
BTW our weirdo plant watering system worked! Harry the parsley plant lives!

**Comment by dghu123** [comment]
Yay Harry!

How was your flight? Mine was pretty uneventful

**Comment by karamar000** [comment]
The flight was kind of an unfortunate adventure. Like the rest of North Carolina, RDU isn't great at snow shoveling. The Raleigh runway was covered in snow, and we had to fly to Charlotte, wait for over an hour, then fly back to Raleigh. Not too bad, but I got home 4 hours later than planned. Fun fact: you can still find an uber driver at 3:30 am on a Wednesday in the middle of a snow storm :) It's weird being home again. It's much quieter and lonelier than when I left.

Also, I can't help thinking about you from the other side of the world :3 How's Beijing? What have you been up to lately?

**Comment by dghu123** [comment]
Oh no! Poor Kara. You have really bad luck with flying.

I’m visiting my grandparents. Beijing is really cold but grandparents keep the apartment at like 80 degrees so its alright. We had peking duck yesterday and it was delicious. I ate way too much.

The other day we saw tianenmen square, which wasnt that interesting. Just a really big plaza with some monuments.

Have classes started yet? Hows your schedule?

**Comment by karamar000** [comment]
I'm trying to enjoy the end of break as much as I can. Classes start on Monday, but this semester I only have classes on Tuesday / Thursday. I'm only taking two classes this semester, so I'm looking forward to more research time. Thinking about all the stuff that has to happen in January has me a little scared, to be honest. I need to finish the draft of my paper, and I already agreed to give two talks. Being busy is kinda what I signed up for, though. It'll all work out :)

I'm glad to hear that you're staying warm and enjoying delicious food. Despite what you say, it sounds like a bunch of interesting adventures! What else are you planning to see/do in Beijing?

**Comment by dghu123** [comment]
You got this Kara, 2 ez 4 martinez

We went to the zoo yesterday and saw the giant pandas. I have a couple pictures of sleepy ones, and i think altogether we have a bunch of animal pictures. I kind of dont like zoos when they have animals i dont think are comfortable in captivity, but these pandas just sleep and eat bamboo so i think its ok.

Today we went to an art district, 798. There was one really cool copper art exhibit with a bunch of statues and even landscapes made of molten copper cooled into intricate shapes. Also in another exhibit there was a very fluffy and cute cat. Then we had chvinese pizza hut which is way better than american pizza hut.

Thought about you a lot too. Cant wait to videochat you! Ill be back in the states by the day after tomorrow.

**Comment by karamar000** [comment]
Thanks for the encouragement! I think that it's working because I even got my code to run yesterday. 

I googled the panda exhibit you went to...OMG SO KYOOT! Sounds like you're having a great adventure! I also hope that your flight home was better than mine. You're such a good plane sleeper, though, you might be able to sleep through any delays :) 

Thinking about you a lot lately. I even had a dream about you the other day. I can't wait to see your beautiful face :3
